%############################################################
%###### Class 'Utils' 
%###### Author  : Nicolas LE GUERROUE
%###### Contact : nicolasleguerroue@gmail.com
%############################################################
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{utils_report}[15/01/2021 Classe personnelle Utils pour document report, V1.0]
\LoadClass[12pt]{report}
\RequirePackage[french]{babel}  
\RequirePackage{Utils/Utils}        %Utils package
%################################################################
